---
- hosts: local
  tasks:
    - name: ensure system is installed
      include_role:
        name: system
        vars_from: "{{ ansible_distribution }}"
#    - name: ensure zsh is installed
#      include_role:
#        name: zsh
#        apply:
#          become: true
#    - name: ensure docker is installed
#      include_role:
#        name: docker
#        apply:
#          become: true
