---
- hosts: local
  tasks:
    - name: ensure system is installed
      include_role:
        name: system
        vars_from: "{{ ansible_distribution }}"
    - name: ensure zsh is installed
      include_role:
        name: zsh
        vars_from: "{{ ansible_distribution }}"
    - name: ensure git is installed
      include_role:
        name: git
        vars_from: "{{ ansible_distribution }}"
